### ISSUE TITLE
feature-request: making the simulator even more realistic

### ISSUE THREAD

**Issue by StefanL38** [wokwi/wokwi-docs#59]
The Wokwi-Simulator offers servos.
This is good, but I have a feature-request:

Real servos need a lot of current. Much more current than an Arduino-onboard-voltage-regulator can offer.
If newcomers that are unexperienced with electronics and build the real thing connected to the Arduinos 5V-pin
The voltage-regulator will do the "magic smoke".

So a really realistic simulation would let burn the arduino's voltage-regulator like the batteries in the DC-Lab of the PHET DC-Lab simulation
![image](https://user-images.githubusercontent.com/8948220/130298872-18403635-062f-458b-b776-295bd69ffefb.png)

http://phet.colorado.edu/sims/html/circuit-construction-kit-dc-virtual-lab/1.1.5/circuit-construction-kit-dc-virtual-lab_all.html
best regards Stefan

**Comment by urish** [comment]
Thanks for the suggestion Stephan! 

I wasn't aware of the PHET DC-Lab, they have a fun interface (though, connecting a dog to your circuit? hmm...)

The simulator doesn't really do any current calculations, since we only do digital simulation. 

That being said, I've heard some requests for "magic smoke" in the simulator. So perhaps we'll add it some day :)
